### ISSUE TITLE
Stack trace missing from example app

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#18]
Would this be because we need source maps? 
![image](https://github.com/MindscapeHQ/raygun4node-aws-lambda/assets/36393794/7eda79e0-5ef2-4efc-b71a-cdd5b07a2b72)

This is my last review point. Everything else looks good!

**Comment by miquelbeltran** [comment]
It has nothing to do with source maps, it's rather because this is how the raygun4node package is implemented.

To provide a stack trace automatically, we have to use `send(Error)` instead of `send(string)`.

I will adjust the AWS Lambda implementation, so any `string` exception is wrapped in an `Error` before being reported.

**Comment by miquelbeltran** [comment]
I improved the example so it will show a more interesting stacktrace by default

![image](https://github.com/MindscapeHQ/raygun4node-aws-lambda/assets/2494376/f1b58360-b99c-4914-8cb3-35288325cce7)
