### ISSUE TITLE
Add a comment to install the `zip` command via chocolaty. 

### ISSUE THREAD

**Issue by sumitramanga** [MindscapeHQ/raygun4node-aws-lambda#37]
I had spent a while on trying to get uit working with a package I installed via the browser. But this caused issue. If I knew to install via Chocolately then it would've saved me some time 😅 

https://github.com/MindscapeHQ/raygun4node-aws-lambda/blob/ae7f91732bad13895990e373291c285658105bbe/example/README.md?plain=1#L17

**Comment by miquelbeltran** [comment]
The script was provided for my own convenience, honestly. I'd assume a developer using this package is already familiar on how to build and distribute AWS Lambda projects as well.

We can add a warning like "You will need to have the `zip` command-line tool installed in order to run this script", or to otherwise build and pack the project by hand.

**Comment by sumitramanga** [comment]
I think my main issue was that I installed manually via the browser for the command instead of using something like Chocolately. Which ended up being a time sink. 

Adding that using a 'command-line package manager and installer' would be more useful :) Also saying that it can me manually zipped is ok too. I think this is still a good tool for all devs working in this space!
